### ISSUE TITLE
PDOException doesn't work with json_encode

### ISSUE THREAD

**Issue by lion328** [riflowth/SkinSystem#20]
Using `json_encode(PDOException)` returns `{"errorInfo":null}`

PHP Version 7.0.18-0ubuntu0.16.04.1

**Comment by LazosPlaying** [comment]
The problem is not `json_encode()` but that PDO's attributes for exception throwing were not set -> ex. `$pdo -> setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);`

Should be fixed in following pull request: [link](https://github.com/riflowth/SkinSystem/pull/22).

**Comment by riflowth** [comment]
Ok, Thanks 👍🏻

**Comment by lion328** [comment]
That PR still doesn't fix the problem in installer. The code in installer even set `PDO::ATTR_ERRMODE` to `PDO::ERRMODE_EXCEPTION` and `json_encode` still returns `{"errorInfo":null}` which showed in installation page as `{ "[error]": { "errorInfo": null } }`.

I also tested by using this code:

```php
<?php

try {
    $pdo = new PDO('abc', 'root', 'root');
    $pdo-setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    echo "Directly print the exception:\n" . $e;
    echo "\n\nWith json_encode: " . json_encode($e);
}

```
and it prints:

```
Directly print the exception:
PDOException: invalid data source name in /var/www/public/check.php:4
Stack trace:
#0 /var/www/public/check.php(4): PDO->__construct('abc', 'root', 'root')
#1 {main}

With json_encode:
{"errorInfo":null}
```

Also for @riflowth; Please let me test the fix before closing the issue. Thanks!

**Comment by LazosPlaying** [comment]
@riflowth this was fixed in #23 

Try the fix out:
|_ https://hastebin.com/anuquzuyin.php
|_ http://phptester.net

Just mark it as solved.

**Comment by lion328** [comment]
@LazosPlaying Looks like it work now. Thanks!
